export * from './Dependencies'
export * from './Footer'
export * from './Name'
export * from './NavBar'
export * from './Stats'
export * from './Title'
export { default as Dependencies } from './Dependencies'
export { default as Footer } from './Footer'
export { default as Name } from './Name'
export { default as NavBar } from './NavBar'
export { default as Stats } from './Stats'
export { default as Title } from './Title'
