name: node_mongo CI

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Run ESLint
        run: pnpm lint
